#pragma once

#include <sdkconfig.h>
#include <driver/gpio.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SI_DISP_BUF_SIZE CONFIG_SI_DISP_PANEL_BUFFER_SIZE
#define SI_DISP_HOR_SIZE 320
#define SI_DISP_VER_SIZE 170

#define NFP190B_DISP_PIN_DATA0 CONFIG_SI_DISP_PANEL_IO_D0  // 39
#define NFP190B_DISP_PIN_DATA1 CONFIG_SI_DISP_PANEL_IO_D1    // 40
#define NFP190B_DISP_PIN_DATA2 CONFIG_SI_DISP_PANEL_IO_D2    // 41
#define NFP190B_DISP_PIN_DATA3 CONFIG_SI_DISP_PANEL_IO_D3    // 42
#define NFP190B_DISP_PIN_DATA4 CONFIG_SI_DISP_PANEL_IO_D4    // 45
#define NFP190B_DISP_PIN_DATA5 CONFIG_SI_DISP_PANEL_IO_D5    // 46
#define NFP190B_DISP_PIN_DATA6 CONFIG_SI_DISP_PANEL_IO_D6    // 47
#define NFP190B_DISP_PIN_DATA7 CONFIG_SI_DISP_PANEL_IO_D7    // 48
#define NFP190B_DISP_PIN_PCLK CONFIG_SI_DISP_PANEL_IO_SCLK      // 8
#define NFP190B_DISP_PIN_CS CONFIG_SI_DISP_PANEL_IO_CS        // 6
#define NFP190B_DISP_PIN_DC CONFIG_SI_DISP_PANEL_IO_DC        // 7
#define NFP190B_DISP_PIN_RST CONFIG_SI_DISP_PANEL_IO_RST       // 5
#define NFP190B_DISP_PIN_BK_LIGHT CONFIG_SI_DISP_PANEL_BKL // 1
#define NFP190B_DISP_PIN_POWER CONFIG_SI_DISP_PANEL_PWR
#define NFP190B_DISP_PIN_RD CONFIG_SI_DISP_PANEL_IO_RD

#ifdef __cplusplus
}
#endif
